{% macro textinput(valueName, label, value="", helptext="", warntext="", placeholder="") -%}
<div class="form-group {% if warntext != "" %} has-error {% endif %}">
<label for="{{valueName}}">{{label|e}}</label>
<input type="text" class="form-control" id="{{valueName}}" placeholder="{{placeholder}}"
       aria-describedby="helpBlock-{{valueName}}" value="{{value}}">
{% if warntext != "" %}
<span id="helpBlock-{{valueName}}" class="help-block">{{warntext|e}}</span>
{% elif helptext != "" %}
<span id="helpBlock-{{valueName}}" class="help-block">{{helptext|e}}</span>
{% endif %}
</div>
{%- endmacro%}