{% extends "master.phtml" %}

{% block head %}
<style>
    .portValue {
        cursor: pointer;
    }


</style>
{% endblock %}

{% block body %}
<h1>Aktueller Status</h1>

<div class="row">
    <div class="col-md-12">
        <h2>Port Status</h2>
        <table class="table table-bordered">
            <thead>
            <tr>
                <td><strong>Port Name</strong></td>
                <td><strong>aktueller Wert</strong></td>
                <td><strong>Status</strong></td>
            </tr>
            </thead>
            <tbody>
            {% for port in portList %}
            <tr>
                <td>{{ port.getName() }}</td>
                <td class="portValue" portname="{{ port.getName() }}">{{
                    port.getState()|string + " " + port.getUnit() }}
                </td>
                {% if port.isPortOK() %}
                <td id="{{ port.getName() }}-isok" class="success"><span class="glyphicon glyphicon-ok"></span>
                    <span class="info-text">O.K.</span>
                </td>
                {% else %}
                <td id="{{ port.getName() }}-isok" class="danger"><span class="glyphicon glyphicon-remove"></span>
                    <span class="info-text">Portfehler</span>
                </td>
                {% endif %}
                <td>
                    <a href="/editPort/?portID={{port.getID()}}"><span class="glyphicon glyphicon-pencil"></span>
                        Bearbeiten</a>
                </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>

<div class="modal fade" id="chartModal" tabindex="-1" role="dialog" aria-labelledby="ModalLabel">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Schließen"><span
                        aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="ModalLabel"></h4>
            </div>
            <div class="modal-body">
                <ul class="nav nav-tabs">
                    <li role="presentation" id="oneMinuteBackChart" class="active chartTabBar"><a
                            href="javascript:void(0)">1 Minute</a></li>
                    <li role="presentation" id="tenMinutesBackChart" class="chartTabBar"><a href="javascript:void(0)">10
                        Minuten</a></li>
                    <li role="presentation" id="oneHourBackChart" class="chartTabBar"><a href="javascript:void(0)">1
                        Stunde</a></li>
                    <li role="presentation" id="oneDayBackChart" class="chartTabBar"><a href="javascript:void(0)">1
                        Tag</a></li>
                    <li role="presentation"><a href="javascript:void(0)">Eigene</a></li>
                </ul>
                <div class="row">
                    <div class="col-md-12" id="portChart">
                        <div class="progress">
                            <div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="45"
                                 aria-valuemin="0" aria-valuemax="100" style="width: 100%">
                            </div>
                        </div>
                        <canvas portname=""></canvas>
                        <div class="alert alert-info" role="alert">
                            <strong>Hinweis!</strong> Aktuell wird die Grafik auf eine begrenzte Anzahl von Datenpunkten
                            beschränkt. Wichtige Messpunkte können daher verloren gehen.
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Schließen</button>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block javascript %}
<script src="/static/js/chart.js"></script>
<script src="/static/js/moment.js"></script>
<script src="static/js/portChart.js"></script>
<script>
    var reloadStatusFunction = function () {
        $.getJSON("/api/currentStatus", function (data) {
            $.each(data, function (key, val) {
                $("#" + val.settings.name + "-state").text(val.state + " " + val.settings.unit);
                if (val.portOK == true) {
                    $("#" + val.settings.name + "-isok").removeClass("danger");
                    $("#" + val.settings.name + "-isok").addClass("success");
                    $("#" + val.settings.name + "-isok > .glyphicon").removeClass("glyphicon-remove");
                    $("#" + val.settings.name + "-isok > .glyphicon").addClass("glyphicon-ok");
                    $("#" + val.settings.name + "-isok > .info-text").text("O.K.");
                } else {
                    $("#" + val.settings.name + "-isok").addClass("danger");
                    $("#" + val.settings.name + "-isok").removeClass("success");
                    $("#" + val.settings.name + "-isok > .glyphicon").addClass("glyphicon-remove");
                    $("#" + val.settings.name + "-isok > .glyphicon").removeClass("glyphicon-ok");
                    $("#" + val.settings.name + "-isok > .info-text").text("Portfehler");
                }
            });
        });
        window.setTimeout(reloadStatusFunction, 1000);
    }
    reloadStatusFunction();

    $.each($('.portValue'), function (key, tag) {
        $(tag).mouseup(function () {
            portName = $(this).attr('portname');
            currentDisplayPortName = portName;
            $('#chartModal').modal('toggle');
            $('.modal-title').text("Chart für " + portName);
            $('.chartTabBar').removeClass("active");
            $('#oneMinuteBackChart').addClass("active");
            drawPortChart('portChart', portName, moment().subtract(1, 'minutes'), moment(), 100);
        });
    });

    $('#oneMinuteBackChart').mouseup(function () {
        $('.chartTabBar').removeClass("active");
        $(this).addClass("active");
        redrawFromNavBar(1, 'minutes');
    });

    $('#tenMinutesBackChart').mouseup(function () {
        $('.chartTabBar').removeClass("active");
        $(this).addClass("active");
        redrawFromNavBar(10, 'minutes');
    });

    $('#oneHourBackChart').mouseup(function () {
        $('.chartTabBar').removeClass("active");
        $(this).addClass("active");
        redrawFromNavBar(1, 'hours');
    });

    $('#oneDayBackChart').mouseup(function () {
        $('.chartTabBar').removeClass("active");
        $(this).addClass("active");
        redrawFromNavBar(1, 'days');
    });

    function redrawFromNavBar(value, type) {
        drawPortChart('portChart', "", moment().subtract(value, type), moment(), 100);
    }

    function redrawPortChart(startDate, endDate, dataPoints) {
        drawPortChart('portChart', "", startDate, endDate, dataPoints);
    }
</script>
{% endblock %}