<!DOCTYPE html>
<html lang="de">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="icon" href="/static/favicon.ico">
    <link rel="icon" type="image/png" href="/static/favicon.png">

    <title>Starter Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">

    <style>
        body {
            padding-top: 50px;
        }
        .row {
            padding-top: 10px;
        }
    </style>

    {% block head %}
    {% endblock %}
</head>

<body>

<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Zeige Navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">ILP Lab Watch</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                {% if page is defined %}
                <li {% if page=="start" %} class="active" {% endif %}><a href="/"><span
                        class="glyphicon glyphicon-home"></span>
                Start</a></li>
                <li {% if page=="verwalten" %} class="active" {% endif %}><a href="/"><span
                    class="glyphicon glyphicon-wrench"></span> Verwalten</a></li>
                <li {% if page=="hinzufuegen" %} class="active" {% endif %}><a href="/addPort"><span
                    class="glyphicon glyphicon-plus"></span> Port Hinzufügen</a></li>
                <li {% if page=="logs" %} class="active" {% endif %}><a href="/"><span
                    class="glyphicon glyphicon-list-alt"></span> Logs</a></li>
                {% else %}
                <li class="active"><a href="/"><span class="glyphicon glyphicon-home"></span> Start</a></li>
                <li><a href="/"><span class="glyphicon glyphicon-wrench"></span> Verwalten</a></li>
                <li><a href="/addPort"><span class="glyphicon glyphicon-plus"></span> Port Hinzufügen</a></li>
                <li><a href="/"><span class="glyphicon glyphicon-list-alt"></span> Logs</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<div class="container">
    {% block body %}
    {% endblock%}
</div>

<script src="/static/js/jquery.js"></script>
<script src="/static/js/bootstrap.min.js"></script>
{% block javascript %}
{% endblock %}
</body>
</html>